### ISSUE TITLE
Build failure – unresolveable dependency org.hisrc.tenra:tenra-core:jar:1.0.1-SNAPSHOT

### ISSUE THREAD

**Issue by Nakaner** [highsource/tenra#3]
I tried to build Tenra (Git commit 477839b) but it fails with:

    [ERROR] Failed to execute goal on project tenra-core: Could not resolve dependen
    cies for project org.hisrc.tenra:tenra-core:jar:1.0.1-SNAPSHOT: Failure to find
    org.hisrc.inspire:inspire-tn-ra-v_3_0:jar:1.0.0-SNAPSHOT in https://oss.sonatype
    .org/content/repositories/snapshots was cached in the local repository, resoluti
    on will not be reattempted until the update interval of sonatype-nexus-snapshots
     has elapsed or updates are forced -> [Help 1]

If `~/.m2` has been deleted before clonging and building it (just to ensure that nothing else interferes), the error message is the following:

    [ERROR] Failed to execute goal on project tenra-core: Could not resolve dependen
    cies for project org.hisrc.tenra:tenra-core:jar:1.0.1-SNAPSHOT: Could not find a
    rtifact org.hisrc.inspire:inspire-tn-ra-v_3_0:jar:1.0.0-SNAPSHOT in sonatype-nex
    us-snapshots (https://oss.sonatype.org/content/repositories/snapshots) -> [Help
    1]

Steps to reproduce:

1. Clone this repository.
2. `cd` into it.
3. Run `mvn clean install -X -e -DperformRelease`

The full output of step 3 (if `~/.m2` has been cleaned before) can be found [here](https://michreichert.de/forum-images/github/highsource/tenra/mvn-error.txt) (689 kB).

**Comment by highsource** [comment]
Ich habe [inspire-schemas](https://github.com/highsource/inspire-schemas) in Maven Central released und POMs korrigiert, soll jetzt gehen.

**Comment by Nakaner** [comment]
Thank you for the quick fix, it works now.
